#!/bin/bash

set -e
set -o pipefail

# Ensure that the GITHUB_TOKEN secret is included
if [[ -z "$GITHUB_TOKEN" ]]; then
  echo "Set the GITHUB_TOKEN env variable."
  exit 1
fi

FILE=${INPUT_FILE}
REPO=${INPUT_REPO}
RELEASE_TAG=${INPUT_RELEASE_TAG}
GITHUB="https://api.github.com"
AUTH_HEADER="Authorization: token ${GITHUB_TOKEN}"

# Ensure that the file path is present
if [[ -z "$FILE" ]]; then
  echo "Pass the name of the asset to download"
  exit 1
fi

# Default Repo if not set == current repo
if [[ -z "$REPO" ]]; then
  REPO = ${GITHUB_REPOSITORY}
fi

# Default release tag, if not set == latest
if [[ -z "$RELEASE_TAG" ]]; then
  # Github should return the latest release first.
  parser=".[0].assets | map(select(.name == \"$FILE\"))[0].id"
else
  parser=". | map(select(.tag_name == \"$RELEASE_TAG\"))[0].assets | map(select(.name == \"$FILE\"))[0].id"
fi;

asset_id=`curl -H "${AUTH_HEADER}" \
               -H "Accept: application/vnd.github.v3.raw" \
               -s $GITHUB/repos/$REPO/releases | jq "$parser"`
if [ "$asset_id" = "null" ]; then
  echo "ERROR: asset id not found"
  exit 1
fi;

curl \
  -L \
  -H "${AUTH_HEADER}" \
  -H "Accept:application/octet-stream" \
  -o "${FILE}" \
  "${GITHUB}/repos/${REPO}/releases/assets/${asset_id}"